[package]
name = "sibiryak"
version = "0.0.1"
authors = ["Boris"]
edition = "2018"

[dependencies]
amethyst = "0.15.1"
log = { version = "0.4.8", features = ["serde"] }

[features]
default = ["vulkan"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
